kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "product-apim-pipeline"
spec:
  source:
    type: "Git"
    git:
      uri: "https://github.com/kevensen/ocp-wso2.git"
  strategy:
    type: "JenkinsPipeline"
    jenkinsPipelineStrategy:
      jenkinsfilePath: jenkinsfiles/product-apim-jenkinsfile
---
kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "carbon-apimgt-pipeline"
spec:
  source:
    type: "Git"
    git:
      uri: "https://github.com/kevensen/ocp-wso2.git"
  strategy:
    type: "JenkinsPipeline"
    jenkinsPipelineStrategy:
      jenkinsfilePath: jenkinsfiles/carbon-apimgt-jenkinsfile
